### ISSUE TITLE
Can i use oak-http-proxy on web-socket requests?

### ISSUE THREAD

**Issue by Relaxe111** [asos-craigmorten/oak-http-proxy#1]
Hello, i have a question. Can i use this middle-ware on web-socket requests?

**Comment by cmorten** [comment]
Hi @Relaxe111 👋 Similarly to https://github.com/asos-craigmorten/opine-http-proxy/issues/5, this module does not support websocket proxying. I’m open to contributions if it’s something you’d want to give a go!

**Comment by cmorten** [comment]
Given this was a question rather than a feature request going to close for now 😄
