### ISSUE TITLE
evt@1.9.12 error

### ISSUE THREAD

**Issue by v0d1n** [asos-craigmorten/oak-http-proxy#2]
# Issue

When I want to use this library as a dependency or even check it out, I get an error on the evt@1.9.12 library.

Setup:

```
deno --version
deno 1.9.1 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

## Details
```
error: TS2612 [ERROR]: Property 'resolve' will overwrite the base property in 'Deferred<undefined>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    public readonly resolve!: () => void;
                    ~~~~~~~
    at https://deno.land/x/evt@v1.9.12/tools/Deferred.ts:57:21
make: *** [build] Error 1
```

**Comment by asos-craigmorten** [comment]
Hi @v0d1n  👋

Thanks for raising this - it's a known issue impacting a few repos following the Deno 1.9.0 release but fortunately has a known fix ( just upgrading dependencies hopefully! ). Will hopefully have time to make the changes and release a fixed version soon!

**Comment by cmorten** [comment]
Hi @v0d1n, please can you try `1.3.0` and see if it resolves your issue. If not then please feel free to re-open with further information!
