### ISSUE TITLE
error: proxying 304 response gives error

### ISSUE THREAD

**Issue by minioin** [asos-craigmorten/oak-http-proxy#4]
When the upstream server returns 304, the proxy still tries to send the body and results in the following error:

```
[uncaught application error]: TypeError - Response with null body status cannot have body
```

**Comment by cmorten** [comment]
Hey @minioin 👋 

Apologies have been slow getting around to this! I believe I have a fix for the issue which will release shortly.

**Comment by cmorten** [comment]
Ok... I _think_ have resolved the issue in https://deno.land/x/oak_http_proxy@2.0.0

Please can you check and reopen the issue if still have issues!
