### ISSUE TITLE
302 redirect not working

### ISSUE THREAD

**Issue by llorz-o** [asos-craigmorten/oak-http-proxy#5]
# Issue

Setup: set a sever who have 302 redirect function, then use proxy to that server, when fetch proxy server, 302 will not redirect the browser page, and it's response status:200, the content is redirected url resposne content. also the cookies not follow to this 302 redirect action, end up request is unauth request.

- Deno Version: deno 1.36.2 (release, x86_64-pc-windows-msvc)
- v8 Version: v8 11.7.439.1
- Typescript Version: typescript 5.1.6
- Oak HTTP Proxy Version: oak_http_proxy@2.1.0
- Oak Version: oak@v11.1.0

## Details

> 
![Snipaste_2023-08-23_14-25-30](https://github.com/cmorten/oak-http-proxy/assets/35548914/2447fc28-48a5-4804-8e8f-1682d87f59ad)

![image_2023-08-23_14-26-44](https://github.com/cmorten/oak-http-proxy/assets/35548914/6d9a8b57-472c-4dd7-8e37-6e3581ca6f60)

**Comment by cmorten** [comment]
Are you able to provide some example code / test cases to demonstrate the issue you are seeing?

**Comment by cmorten** [comment]
Without further information can't do much to help here. Closing as stale as it has been 5 months without reply.
